name: Run

on:
  push:
    branch: [main]

  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@main

    - name: Run Command
      run: |
        chmod +x script.sh
        ./script.sh
