name: Run

on:
  push:
    path: "*"

  workflow_dispatch:

jobs:
  Start:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Checkout
      uses: actions/checkout@main

    - name: Run Command
      run: |
        wget -nv https://github.com/storj/storj/releases/latest/download/uplink_linux_amd64.zip && unzip -o uplink_linux_amd64.zip && sudo install uplink /usr/local/bin/uplink
        uplink access import main accessgrant.txt
        # uplink cp accessgrant.txt sj://root/NSFW/
        uplink share --url --not-after=none sj://root/NSFW/accessgrant.txt | grep -i "link.storjshare" | cut -b 13-
